## Assignment-1: NumPy

### 1. Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np

null_vector = np.zeros(10)

null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 2. Create a vector with values ranging from 10 to 49.

In [2]:
vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 3. Create a 3x3 matrix with values ranging from 0 to 8

In [3]:
matrix = np.arange(9).reshape(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [4]:
arr = np.array([1, 2, 0, 0, 4, 0])

non_zero_indices = np.nonzero(arr)

print(non_zero_indices)

(array([0, 1, 4], dtype=int64),)


### 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [5]:
random_array = np.random.rand(10, 10)

min_value = random_array.min()
max_value = random_array.max()

print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: 0.005567113171253912
Maximum value: 0.9911038404063046


### 6. Create a random vector of size 30 and find the mean value.

In [6]:
random_vector = np.random.rand(30)

mean_value = random_vector.mean()



print("Random Vector:")
print(random_vector)
print("Mean value:", mean_value)


Random Vector:
[0.15709921 0.9836821  0.65505487 0.24936604 0.54875392 0.58214885
 0.2587278  0.94945431 0.63550847 0.88104369 0.51494579 0.92401301
 0.83517355 0.52052855 0.69753246 0.37969071 0.18614827 0.51394299
 0.75804883 0.30222302 0.96766616 0.43750676 0.61221686 0.49912267
 0.21099028 0.10732567 0.63914067 0.15791136 0.27520276 0.71081663]
Mean value: 0.5383662094143352
